
export enum AlertTexts {
  log_in = 'Uživatel přihlášen',
  log_out = 'Uživatel odhlášen',
  log_in_failed = 'Přihlášení selhalo',
  event_sign_in = 'Uživatel přihlášen na událost ',
  event_sign_out = 'Uživatel odhlášen z události ',
  fail = 'Chyba',
  event_udpated = 'Událost upravena',
  event_created = 'Událost vytvořena',
  event_copied = 'Událost zkopírována',
  event_deleted = 'Událost smazána',
  event_reg_updated = 'Registrace upravena',
  event_reg_all = 'Hromadné potvrzení ok',
  notice_created = 'Příspěvek vytvořen',
  notice_deleted = 'Příspěvek smazán',
  notice_updated = 'Příspěvek upraven',
  article_created = 'Článek vytvořen',
  article_deleted = 'Článek smazán',
  article_updated = 'Článek upraven',
  pic_format_fail = 'Špatný formát obrázku',
  fail_check_console = 'Chyba, zkontroluj consoli.',
  member_created = 'Člen vytvořen.',
}
